{
  "$schema": "https://raw.githubusercontent.com/rwx-research/test-results-schema/main/v1.json",
  "framework": {
    "language": "Ruby",
    "kind": "Cucumber"
  },
  "summary": {
    "status": {
      "kind": "failed"
    },
    "tests": 3,
    "otherErrors": 1,
    "retries": 0,
    "canceled": 0,
    "failed": 0,
    "pended": 0,
    "quarantined": 0,
    "skipped": 0,
    "successful": 3,
    "timedOut": 0,
    "todo": 0
  },
  "tests": [
    {
      "name": "Rule Sample \u003e With a failing after hook \u003e this will pass",
      "lineage": [
        "Rule Sample",
        "With a failing after hook",
        "this will pass"
      ],
      "location": {
        "file": "features/rule.feature",
        "line": 44
      },
      "attempt": {
        "durationInNanoseconds": 12000,
        "meta": {
          "elementStart": "features/rule.feature:41",
          "stepLocation": "features/step_definitions/steps.rb:1",
          "tags": [
            {
              "name": "@feature_tag",
              "line": 1
            },
            {
              "name": "@rule_tag",
              "line": 4
            },
            {
              "name": "@failing_after_hook",
              "line": 40
            }
          ]
        },
        "status": {
          "kind": "successful"
        }
      }
    },
    {
      "name": "Rule Sample \u003e With a failing after hook \u003e I do an action",
      "lineage": [
        "Rule Sample",
        "With a failing after hook",
        "I do an action"
      ],
      "location": {
        "file": "features/rule.feature",
        "line": 44
      },
      "attempt": {
        "durationInNanoseconds": 7000,
        "meta": {
          "elementStart": "features/rule.feature:41",
          "stepLocation": "features/step_definitions/steps.rb:9",
          "tags": [
            {
              "name": "@feature_tag",
              "line": 1
            },
            {
              "name": "@rule_tag",
              "line": 4
            },
            {
              "name": "@failing_after_hook",
              "line": 40
            }
          ]
        },
        "status": {
          "kind": "successful"
        }
      }
    },
    {
      "name": "Rule Sample \u003e With a failing after hook \u003e some results should be there",
      "lineage": [
        "Rule Sample",
        "With a failing after hook",
        "some results should be there"
      ],
      "location": {
        "file": "features/rule.feature",
        "line": 44
      },
      "attempt": {
        "durationInNanoseconds": 30000,
        "meta": {
          "elementStart": "features/rule.feature:41",
          "stepLocation": "features/step_definitions/steps.rb:12",
          "tags": [
            {
              "name": "@feature_tag",
              "line": 1
            },
            {
              "name": "@rule_tag",
              "line": 4
            },
            {
              "name": "@failing_after_hook",
              "line": 40
            }
          ]
        },
        "status": {
          "kind": "successful"
        }
      }
    }
  ],
  "otherErrors": [
    {
      "location": {
        "file": "features/step_definitions/steps.rb",
        "line": 28
      },
      "message": "failed in after hook (RuntimeError)\n./features/step_definitions/steps.rb:29:in `After'",
      "meta": {
        "type": "after hook"
      }
    }
  ]
}
